const API_URL = import.meta.env.VITE_FORSIKATEL_API_URL
export const API_REGISTER = `${API_URL}/users/register`
export const API_LOGIN = `${API_URL}/users/login`
export const API_HADIST_KULTUM = `${API_URL}/hadist-kultum/`
export const API_SETOR_NGAJI = `${API_URL}/setoran-ngaji/`
export const API_DASHBOARD = `${API_URL}/dashboard/`
export const API_AUTH = `${API_URL}/users/authenticate`
export const API_PROGRESS_CHART = `${API_URL}/setoran-ngaji/chart_ngaji`
export const API_PROGRESS = `${API_URL}/progress`
export const API_REKAP = `${API_URL}/recap/`